### ISSUE TITLE
Make tutorial and notebook text pedagogical

### ISSUE THREAD

**Issue by bnord** [lsst-epo/citizen-science-notebooks#26]

**Comment by bnord** [comment]
Documentation sufficient such that it can be approached in a “stand alone” way

**Comment by bnord** [comment]
Includes examples of retrieving “common” data types from RSP?

**Comment by clareh** [comment]
Just making a note of when we get to this, important to consider the error messages and read outs from the cells (consider any changes to the "send data" cell responses?)

**Comment by beckynevin** [comment]
I'm going to close this issue; it was a duplicate of discussion #42 and was addressed in the clarifying_pedagogy pull request #48
