### ISSUE TITLE
Make sure the notebooks follow the Rubin guidelines for user tutorials

### ISSUE THREAD

**Issue by beckynevin** [lsst-epo/citizen-science-notebooks#35]
[https://rtn-045.lsst.io/](https://rtn-045.lsst.io/)

Including flake8, inclusive language, etc.

**Comment by jsv1206** [comment]
Guidelines for User Tutorials:

https://rtn-045.lsst.io/#jupyter-notebook-format-style-and-code-standards

**Comment by beckynevin** [comment]
This is a replicate of issue #64 so I am going to close
