### ISSUE TITLE
Flake8 error in Citizen_Science_SDK.ipynb

### ISSUE THREAD

**Issue by jsv1206** [lsst-epo/citizen-science-notebooks#40]
**Describe the bug**
Checking PEP8 coding style in  variable_stars.ipynb following instructions from Section 3.8 in
[https://rtn-045.lsst.io/#jupyter-notebook-format-style-and-code-standards](https://rtn-045.lsst.io/#jupyter-notebook-format-style-and-code-standards)

I get the error in %run Citizen_Science_SDK.ipynb cell

**To Reproduce**
Steps to reproduce the behavior, written in imperative mood:
1. Go to 'variable_stars' branch
2. Click on 'variable_stars.ipynb'
3. Scroll down to '%run Citizen_Science_SDK.ipynb' cell

**Comment by ericdrosas87** [comment]
I'm just starting to take a look at this now, will provide an update after I've done some research

**Comment by ericdrosas87** [comment]
@jsv1206 Can you post a screenshot of the error you are seeing?

**Comment by jsv1206** [comment]
Attached is the error I get.
![flake8_error_1](https://user-images.githubusercontent.com/13951429/235533875-b0be6448-698d-499c-8400-6a497fac05a7.png)
![flake8_error_2](https://user-images.githubusercontent.com/13951429/235533873-ef07a20e-d6f4-4383-9f03-19944a486f86.png)
![flake8_error_3](https://user-images.githubusercontent.com/13951429/235533871-7df52509-a186-4ad6-8912-89ca6b45dc95.png)

**Comment by ericdrosas87** [comment]
After troubleshooting with @jsv1206 , the resolution was to include the following two lines in both the first cell of the SDK notebook AND the cell of the variable stars notebook that imports the SDK notebook:

```
%load_ext pycodestyle_magic
%flake8_on
```

It is unclear why these lines need to be repeated or if this is intended behavior of the Flake8 or PEP package. Further research/discovery is needed to make that determination, but Sree should now be unblocked from her work.

**Comment by jsv1206** [comment]
This issue is resolved by including the following in the SDK notebook. This has to be in the same first cell as the other installations.

`%load_ext pycodestyle_magic
%flake8_on`

Include the following in the Testing or variable_stars notebook. This has to be in the first cell with log in details to Zooniverse.

`%load_ext pycodestyle_magic
%flake8_on
import logging
logging.getLogger("flake8").setLevel(logging.FATAL)`

**Comment by jsv1206** [comment]
SDK notebook cell:
![SDK_notebook](https://user-images.githubusercontent.com/13951429/235945782-e2034f30-3293-4f3b-99a1-490bfe2cb000.png)

Main notebook cell:
![main_notebook](https://user-images.githubusercontent.com/13951429/235945801-42dcadd9-527a-4ded-a74e-e2a4bdaeb74d.png)
