### ISSUE TITLE
Add notebook listing and short summary to README.md

### ISSUE THREAD

**Issue by aprajita** [lsst-epo/citizen-science-notebooks#41]
**Describe the bug**
Would be useful if the README summarised the available notebooks i.e a listing along with a short summary for each notebook added.

**Comment by aprajita** [comment]
I think I submitted this as the wrong type of issue and now can't seem to edit the labels, more of an enhancement rather than a bug.

**Comment by ericdrosas87** [comment]
No worries @aprajita I updated the tags label for you. I can add an outline to the `README.md`, but it probably makes more sense for the scientists to describe what the notebooks are for - what do you think @clareh?

**Comment by bnord** [comment]
This will depend on what we scripts/functions we make and what notebooks we make. 

Ref https://github.com/lsst-epo/citizen-science-notebooks/discussions/42#discussioncomment-6004362

**Comment by beckynevin** [comment]
Hi @aprajita I took a quick swipe at this in the PR #50. Let me know if you have any additional suggestions for how to make this more clear. I can definitely give more details.

**Comment by beckynevin** [comment]
I already merged this
