### ISSUE TITLE
Refactor the `__cit_sci_data_type` variable of the Citizen_Science_Testing notebook and instead create multiple `send_data()` functions

### ISSUE THREAD

**Issue by ericdrosas87** [lsst-epo/citizen-science-notebooks#45]
Currently, in the `Citizen_Science_Testing` notebook, and thus other notebooks that are being on this notebook, there exists a variable right before the `send_data()` call. This is an unnecessary complication in the code workflow and can be refactored out so that the notebook users do not need to concern themselves with it. Rather, a separate `send_data()` functions will be created, and should be for each additional use case that gets added to the citSci notebook repository. Right now the primary use cases are:

1. Sending image data, either flipbook or single image
<s>2. Sending tabular data</s>

I will create two functions to accommodate for these use cases and remove the aforementioned variable from the Testing notebook.

Update June 22, 2023: My mistake, the `Citizen_Science_TAP_Tutorial` notebook was created very specifically to demonstrate the ability to transfer tabular data to the EDC as part of NFS requirements verifications and not for transferring tabular data for a citizen science project on the Zooniverse platform. That being said, the TAP notebook can be used as a starting point for fleshing out that use case function which can be tracked with a separate issue.

**Comment by ericdrosas87** [comment]
This has been implemented and merged into `main` as part of 54ce85b1a1df310281b4abc71b526ab4304bbf8a

**Comment by ericdrosas87** [comment]
@clareh @bnord @jsv1206 @beckynevin See update above in first comment. Otherwise, this change has been implemented for the SDK and Testing notebooks, the Testing notebook can be used as a template for modifying the `variable_stars` notebook and any others that are floating around out there. Essentially, all that is needed is to delete the `__cit_sci_data_type` and call the function `send_image_data()` instead of `send_data()`

**Comment by beckynevin** [comment]
Awesome, I'll make these same changes in the pedagogy branch as well.
