### ISSUE TITLE
butler-secret error while running Citizen_Science_Testing.ipynb

### ISSUE THREAD

**Issue by jsv1206** [lsst-epo/citizen-science-notebooks#53]
**Describe the bug**
I got the latest version of Citizen_Science_Testing.ipynb in main and I get the error message about butler-secret.  Please see the screenshot for the error message.
I didn't have this issue from the previous version of the code.

**Screenshots**
![error1](https://github.com/lsst-epo/citizen-science-notebooks/assets/13951429/a2068dc7-96fe-483a-b271-e4a8d5f51e93)
![error2](https://github.com/lsst-epo/citizen-science-notebooks/assets/13951429/3e296f39-ca44-4aa6-b270-c1572380cb03)

**Comment by ericdrosas87** [comment]
@jsv1206 and also @beckynevin @bnord @clareh the location of the secret has indeed changed in the last couple days (it's not owned by us and is owned by the DM SQuaRE team). This change has only been reflected in the #52 will address this. I can implement a temp fix this morning though until I merge #52 which will just modify the path referenced in `rubin_citsci_core_pipeline.py`. If you need urgent unblocking of the issue please message me directly on Slack!

**Comment by ericdrosas87** [comment]
Temp fix going in with #54

**Comment by ericdrosas87** [comment]
@jsv1206 #54 has been merged and the `main` branch is now ready for testing. Only the `rubin_citsci_core_pipeline.py` changed so you should just be able to drop that into your Notebook Aspect filesystem.

**Comment by beckynevin** [comment]
Is this problem resolved? Can we close this issue?
