### ISSUE TITLE
variable_stars images

### ISSUE THREAD

**Issue by jsv1206** [lsst-epo/citizen-science-notebooks#70]
- The query seems to return variable stars but this needs to be verified
- Randomly selecting 5 images might not guarantee we see the star as we might be selecting the lower flux
- the pixel scale and pixel centre varies between different images of the same star even if the ra and dec are the same

**Comment by jsv1206** [comment]
Some useful links for debugging and visualization:

https://dp0-2.lsst.io/data-products-dp0-2/index.html
https://dm.lsst.org/sdm_schemas/browser/dp02.html

**Comment by beckynevin** [comment]
Do you think the new notebook tutorial will help with resolving the second two points? Should I work on separately verifying the query?

**Comment by jsv1206** [comment]
I am not sure if we want to go through this route of making co-add images for each star. Maybe we can leave it up to the PI and give the tutorial notebook reference in the text. I am thinking we can continue with selecting random `calexp` images.

The reason, I believe for point #3 i.e. the randomly selected images having different pixel centre etc is because the images are coming from different CCDs which have to be calibrated to get to the same sky map. This is all done in the `deepCoadd `pipeline 
"To create a custom coadd, only two steps need to be rerun: `makeWarp` and `assembleCoadd`."

**Comment by jsv1206** [comment]
Same goes with point 2. We can leave it to the PI to select/coadd the images they want to show. We can just provide the infrastructure to send flipbook images.

**Comment by jsv1206** [comment]
@beckynevin Go ahead and check the query I currently have to get the variable stars and the flux for each variable star. From what I see, it looks fine.

**Comment by beckynevin** [comment]
Okay I've been looking through the query_flux() example and it looks good - a good match to tutorial notebook 7b. I was thinking we should add a similar caveat to this in the header or maybe somewhere in the analysis section of the variable stars tutorial. It could reference our thinking that this notebook is not doing the harder step of custom-creating deepcoadds, that can be left to the scientist. We're simply demonstrating how to send a multi-image dataproduct to Zooniverse:
![image](https://github.com/lsst-epo/citizen-science-notebooks/assets/26393168/4ee951c9-16ce-41ab-9fc4-2d024f17ecaf)

**Comment by beckynevin** [comment]
We could also refer them to this notebook (7b) that goes into the Lomb-Scargle periodogram example.

**Comment by beckynevin** [comment]
> I am not sure if we want to go through this route of making co-add images for each star. Maybe we can leave it up to the PI and give the tutorial notebook reference in the text. I am thinking we can continue with selecting random `calexp` images.
> 
> The reason, I believe for point 3 i.e. the randomly selected images having different pixel centre etc is because the images are coming from different CCDs which have to be calibrated to get to the same sky map. This is all done in the `deepCoadd `pipeline "To create a custom coadd, only two steps need to be rerun: `makeWarp` and `assembleCoadd`."

So if you end up going the no-deepcoadd route (only using calexp images), will they just always be misaligned? In other words, is there no way to align them without going through the coadd reduction process?

**Comment by jsv1206** [comment]
For the `query_stars` function,

1. To query more than one star we need to change the `AND CONTAINS` part of the query to <= 1. That should query stars within the circle
2. The different tables and the columns in each table is listed in https://dm.lsst.org/sdm_schemas/browser/dp02.html#Visit
This ID is used to `JOIN` tables
3. AS you said, it would be nice to explain this query. I wrote most of it. Some helpful references are: link in 2 and tutorial `07b_Variable_Star_Lightcurves.ipynb`
4. `truth_type` points to the type of object i.e. star, galaxy or SNE. Refer to the link in 2 for more details
5. We query` matches_objectId` to `JOIN` on the `Object Table` which has the flux information i.e. we use this ID in the `query_flux` function

**Comment by beckynevin** [comment]
@beckynevin what to do about the plotting utility functions that are packaged in rubin.citsci

**Comment by beckynevin** [comment]
There's some element of randomness to this query - is there a way to get rid of this random element so we can save an output and verify that the brightness change is visible going forward?

**Comment by beckynevin** [comment]
Update on this - the individual calexp images look misaligned in WCS because the WCS grid currently centers on each calexp image, even though we are giving it a coordinate. In other words, the image itself is correctly centered, while the WCS is not.

To address some of the above discussion; it is clear that calexp is the image type we want to be sending; deepcoadds would contradict the purpose of what we're trying to do, since deepcoadds smooth out variable objects, which by definition only exist in the difference (calexp) images, not in the deepcoadds.

**Comment by beckynevin** [comment]
I'm going to close this issue and open a new one because I am now having the opposite issue; that the images are centered on the same pixel but the WCS is misaligned.
