### ISSUE TITLE
Getting an error while sending data

### ISSUE THREAD

**Issue by jsv1206** [lsst-epo/citizen-science-notebooks#74]
**Describe the bug**
I get the error while running `Citizen_Science_Testing.ipynb` in `main` branch. This was working with the previous version.

I tried sending the data into an existing projects after deleting the subject sets there. I also tried sending data to a new project. Both of them give the same error

Please see the error attached with this issue.
![citsci_error](https://github.com/lsst-epo/citizen-science-notebooks/assets/13951429/3423f371-444d-478a-a5ae-d065f7206a9b)

**Comment by ericdrosas87** [comment]
Apologies about the issue - the backend service is down in Google Cloud and we're not really sure why at the moment. I'm currently redeploying the backend service to see if that fixes thing and I will post an update once the deploy finishes.

**Comment by ericdrosas87** [comment]
@jsv1206 Redeploying the service fixed the issue. Please try using the notebook again and let me know if you run into any further issues.

**Comment by beckynevin** [comment]
Okay I'm now trying to rerun the notebook - it looks like I'm getting the following error upon loading the packages - should I make this into a separate issue?

```
!pip install --upgrade --force-reinstall --no-deps rubin.citsci --quiet
# general python packages
from matplotlib import image as mpimg
import matplotlib.pyplot as plt

from rubin.citsci import pipeline

# utils is the citsci plotting and other utilities
import utils

plt.style.use('tableau-colorblind10')
```


```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 5
      2 from matplotlib import image as mpimg
      3 import matplotlib.pyplot as plt
----> 5 from rubin.citsci import pipeline
      7 # utils is the citsci plotting and other utilities
      8 import utils

File ~/.local/lib/python3.11/site-packages/rubin/citsci/pipeline.py:23
     21 from IPython.display import display
     22 import google.cloud.storage as storage
---> 23 import panoptes_client
     24 from panoptes_client import Project, SubjectSet, Classification
     26 class CitSciPipeline:

ModuleNotFoundError: No module named 'panoptes_client'
```

**Comment by beckynevin** [comment]
Okay trying to rerun again on main, I'm getting a panoptes client error when I run this cell:
```
!pip install --upgrade --force-reinstall --no-deps rubin.citsci --quiet
import utils

email = "beckynevin@gmail.com" # Email associated with Zooniverse account 
slug_name = "rebecca-dot-nevin/test-project" # Do not include the leading forward-slash, see above 

from rubin.citsci import pipeline
print("Loading and running utilities to establish a link with Zooniverse")
print("Enter your Zooniverse username followed by password below")
cit_sci_pipeline = pipeline.CitSciPipeline()
cit_sci_pipeline.login_to_zooniverse(slug_name, email)
```

Here's the error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[4], line 4
      1 email = "beckynevin@gmail.com" # Email associated with Zooniverse account 
      2 slug_name = "rebecca-dot-nevin/test-project" # Do not include the leading forward-slash, see above 
----> 4 from rubin.citsci import pipeline
      5 print("Loading and running utilities to establish a link with Zooniverse")
      6 print("Enter your Zooniverse username followed by password below")

File ~/.local/lib/python3.11/site-packages/rubin/citsci/pipeline.py:23
     21 from IPython.display import display
     22 import google.cloud.storage as storage
---> 23 import panoptes_client
     24 from panoptes_client import Project, SubjectSet, Classification
     26 class CitSciPipeline:

ModuleNotFoundError: No module named 'panoptes_client'
```

**Comment by ericdrosas87** [comment]
> ModuleNotFoundError: No module named 'panoptes_client'

Yeah I saw this issue too for some reason, I had to go into a terminal tab and manually run `pip install panoptes_client` although I shouldn't have had to do that considering the citSci backend PyPI package requires this as a dependency. I thought it was just a _me_ issue though, now that I see it's affecting you too @beckynevin and probably the others I'll follow-up with the SQRE team.

But yes I think this should be tracked as a separate issue. Something to the extent of: "panoptes_client not installed as part of rubin.citsci dependency installation"

**Comment by ericdrosas87** [comment]
@beckynevin Hang tight on creating that new issue. I chatted a bit with the SQRE team and the `panoptes_client` wasn't being installed due to an issue with the install command (my fault). Through this discussion SQRE recommended that the installation for the `rubin.citsci` package occur in a terminal tab rather than as a notebook shell command. I went ahead and made this change with #76. Please do a fresh `git pull` and retry when you have moment.

**Comment by beckynevin** [comment]
Okay that works with the pip install command in the terminal. Will users just need to run this command the first time they run the notebook?

**Comment by ericdrosas87** [comment]
> Okay that works with the pip install command in the terminal. Will users just need to run this command the first time they run the notebook?

When the run the notebook for the first time, and periodically as the RSP updates the notebook environment in such a way that users' installed packages need to be reinstalled (as was recently the case, hence the bug appearing).

**Comment by ericdrosas87** [comment]
Also: Melissa Graham is aware of the `rubin.citsci` package and would like to see it installed by default in the Notebook Aspect environment - so this manual installation won't be necessary long-term. We're still iterating too much on the `rubin.citsci` package for that to make sense for the foreseeable future though.

**Comment by jsv1206** [comment]
I get the following error (attached screenshots) during the installation using `pip install rubin.citsci`. 

I run this after doing a `git pull` in `main`

`from rubin.citsci import pipeline` gives `No module named 'rubin'` error

![citsci_error1](https://github.com/lsst-epo/citizen-science-notebooks/assets/13951429/df8b1429-8020-4b22-b585-f51a3cb55f26)
![citsci_error2](https://github.com/lsst-epo/citizen-science-notebooks/assets/13951429/eb4b1093-4b66-445f-924f-2ef78c68eee7)

**Comment by ericdrosas87** [comment]
@jsv1206 Can you please restart the Notebook kernel and try again?

**Comment by beckynevin** [comment]
I just tried in main and am not getting the above issue.

**Comment by beckynevin** [comment]
@ericdrosas87 I'm going to close this issue, especially since Sree is no longer working on the notebooks.
